import fs from 'node:fs/promises';
import path from 'node:path';
import {analyzeMarket,blendProbabilities,clamp,brierScore,logLoss,VERSION} from './quant-engine.mjs';
const ROOT=process.cwd(), DATA=path.join(ROOT,'data');
const ODDS_KEY=process.env.ODDS_API_KEY||'', BDL_KEY=process.env.BDL_API_KEY||'';
const NOW=new Date(); const ISO=NOW.toISOString();
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^a-z0-9]+/g,' ').trim();
const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const sd=a=>{if(a.length<2)return 10;const m=avg(a);return Math.sqrt(avg(a.map(x=>(x-m)**2)))};
async function fetchJson(url,{headers={},retries=2}={}){let last;for(let i=0;i<=retries;i++){try{const c=new AbortController();const t=setTimeout(()=>c.abort(),15000);const r=await fetch(url,{headers,signal:c.signal});clearTimeout(t);if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(e){last=e;if(i<retries)await new Promise(r=>setTimeout(r,800*(i+1)))} }throw last}
function baseBoard(league,source,note=''){return {meta:{league,status:'LIVE_READY',model_health:'COLD',data_health:'NO_FEED',market_health:'NO_FEED',risk_mode:'PAPER_ONLY',updated_at:ISO,source,model_version:`${VERSION}-${league}`,note},stats:{closed_picks:0,hit_rate:null,roi:null,brier:null,log_loss:null,avg_clv:null,max_drawdown_units:0},risk:{exposure_units:0,max_exposure_units:league==='NBA'?3:2,correlation_guard:'ON',mode:'PAPER_ONLY'},learning:{calibration:{active:false},drift:{health:'COLD'},challenger:{status:'TESTING',sample:0,note:'Promozione solo out-of-sample.'}},radar:[],upcoming:[],history:[],integrity:{strict_no_fabrication:true,generated_at:ISO}}}
async function previous(file){try{return JSON.parse(await fs.readFile(path.join(DATA,file),'utf8'))}catch{return null}}
function metrics(history=[]){const settled=history.filter(x=>x.status==='SETTLED'&&Number.isFinite(x.model_prob)&&typeof x.outcome==='boolean');const bets=settled.filter(x=>x.verdict==='PAPER BET'&&Number.isFinite(x.profit_units));const rows=settled.map(x=>({prob:x.model_prob,outcome:x.outcome}));const stake=bets.reduce((s,x)=>s+(x.stake_units||1),0), profit=bets.reduce((s,x)=>s+x.profit_units,0);let eq=0,peak=0,dd=0;for(const x of bets){eq+=x.profit_units||0;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}return {closed_picks:settled.length,hit_rate:bets.length?bets.filter(x=>x.profit_units>0).length/bets.length:null,roi:stake?profit/stake:null,brier:brierScore(rows),log_loss:logLoss(rows),avg_clv:null,max_drawdown_units:dd}}
function modelFromGames(games){const m=new Map();const get=n=>{const k=norm(n);if(!m.has(k))m.set(k,{name:n,elo:1500,games:0,margins:[],recent:[],last:null});return m.get(k)};for(const g of games.sort((a,b)=>new Date(a.date)-new Date(b.date))){if(!g.home||!g.away||!Number.isFinite(g.hs)||!Number.isFinite(g.as))continue;const h=get(g.home),a=get(g.away),homeAdj=58,ex=1/(1+10**(-((h.elo+homeAdj)-a.elo)/400)),act=g.hs>g.as?1:0,k=18,delta=k*(act-ex);h.elo+=delta;a.elo-=delta;h.games++;a.games++;h.margins.push(g.hs-g.as);a.margins.push(g.as-g.hs);h.recent.push(g.hs-g.as);a.recent.push(g.as-g.hs);if(h.recent.length>10)h.recent.shift();if(a.recent.length>10)a.recent.shift();h.last=g.date;a.last=g.date}return m}
function probs(model,home,away){const h=model.get(norm(home))||{elo:1500,games:0,margins:[],recent:[]},a=model.get(norm(away))||{elo:1500,games:0,margins:[],recent:[]};const elo=1/(1+10**(-((h.elo+58)-a.elo)/400)),form=1/(1+Math.exp(-(avg(h.recent)-avg(a.recent)+2)/10)),margin=1/(1+Math.exp(-(avg(h.margins.slice(-30))-avg(a.margins.slice(-30))+2)/12));const parts=[elo,form,margin],p=blendProbabilities(parts,[1.3,1,.9]),dis=Math.max(...parts)-Math.min(...parts),unc=clamp(.03+(sd(h.recent)+sd(a.recent))/180+Math.max(0,12-Math.min(h.games,a.games))/140,.025,.14);return {p,parts,dis,unc,sample:Math.min(h.games,a.games)}}
function markets(ev){const rows=[];for(const b of ev.bookmakers||[]){const m=(b.markets||[]).find(x=>x.key==='h2h');const ho=m?.outcomes?.find(x=>norm(x.name)===norm(ev.home_team)),ao=m?.outcomes?.find(x=>norm(x.name)===norm(ev.away_team));if(ho?.price>1&&ao?.price>1)rows.push({book:b.title,home:+ho.price,away:+ao.price,updated:b.last_update||m.last_update})}if(!rows.length)return null;const latest=Math.max(...rows.map(r=>new Date(r.updated||0).getTime()).filter(Boolean),0);return {books:rows.length,bestHome:Math.max(...rows.map(r=>r.home)),bestAway:Math.max(...rows.map(r=>r.away)),ageMin:latest?(Date.now()-latest)/60000:999}}
function buildEntries(league,odds,games,{availability='LIMITED',requireAvailability=false}={}){const model=modelFromGames(games);const upcoming=[],radar=[];for(const ev of odds){if(new Date(ev.commence_time)<=NOW)continue;const p=probs(model,ev.home_team,ev.away_team),mk=markets(ev);radar.push({league,away_team:ev.away_team,home_team:ev.home_team,start_at:ev.commence_time,pre_status:'LIVE RADAR',favorite_name:p.p>=.5?ev.home_team:ev.away_team,favorite_prob:Math.max(p.p,1-p.p),confidence:clamp(100-p.unc*100-p.dis*50,0,100),priority:clamp(55+Math.abs(p.p-.5)*100+p.sample,0,100),preview_reason:'Elo + forma + margin profile; decisione separata dalle quote.'});if(!mk)continue;const homePick=p.p>=.5,pick=homePick?ev.home_team:ev.away_team,probParts=homePick?p.parts:p.parts.map(x=>1-x),op=homePick?mk.bestHome:mk.bestAway,oo=homePick?mk.bestAway:mk.bestHome;const dq=clamp(52+Math.min(30,p.sample*1.6)+(availability==='VERIFIED'?12:6),45,95);const penalty=availability==='VERIFIED'?0:.018;const a=analyzeMarket({engineProbs:probParts,engineWeights:[1.3,1,.9],oddsPick:op,oddsOther:oo,uncertainty:p.unc,disagreement:p.dis,dataQuality:dq,marketBooks:mk.books,oddsAgeMin:mk.ageMin,availabilityStatus:availability,requireAvailability,availabilityPenalty:penalty,marketStability:clamp(62+mk.books*5-Math.min(25,mk.ageMin/5),35,96)});upcoming.push({league,away_team:ev.away_team,home_team:ev.home_team,start_at:ev.commence_time,predicted_at:ISO,audit_id:`${league}-${String(ev.id||'').slice(0,10)}-${ISO.slice(0,13)}`,verdict:a.decision,pick_name:`${pick} ML`,best_odds:op,raw_ev:a.rawEV,robust_ev:a.robustEV,model_prob:a.modelProb,market_prob:a.marketProb,edge:a.edge,confidence:a.confidence,data_quality:dq,market_books:mk.books,odds_age_min:mk.ageMin,model_disagreement:p.dis,uncertainty:p.unc,stake_units:a.stakeUnits,availability_status:availability,reason_codes:a.gateReasons,wait_reason:a.gateReasons.length?`Gate: ${a.gateReasons.join(', ')}`:null,case_for:`Modello multi-motore e prezzo de-vig convergono su ${pick}.`,case_against:availability==='VERIFIED'?'Rischio residuo: varianza e line movement.':'Disponibilità roster non completamente verificata: confidence e stake penalizzati.'})}return {upcoming,radar}}
async function oddsFor(key){if(!ODDS_KEY)return [];return fetchJson(`https://api.the-odds-api.com/v4/sports/${key}/odds/?regions=eu,us&markets=h2h&oddsFormat=decimal&apiKey=${encodeURIComponent(ODDS_KEY)}`)}
async function nbaGames(){if(!BDL_KEY)return [];const end=new Date(Date.now()-86400000).toISOString().slice(0,10),start=new Date(Date.now()-420*86400000).toISOString().slice(0,10);const j=await fetchJson(`https://api.balldontlie.io/v1/games?start_date=${start}&end_date=${end}&per_page=100`,{headers:{Authorization:BDL_KEY}});return (j.data||[]).filter(g=>g.status==='Final'||Number.isFinite(+g.home_team_score)).map(g=>({date:g.date,home:g.home_team?.full_name,away:g.visitor_team?.full_name,hs:+g.home_team_score,as:+g.visitor_team_score}))}
function pick(o,...keys){for(const k of keys){const v=k.split('.').reduce((a,x)=>a?.[x],o);if(v!==undefined&&v!==null&&v!=='')return v}return null}
function parseELGame(g){const home=pick(g,'local.club.name','local.club.clubName','local.club.clubPermanentName','local.name','homeTeam.name','home.name'),away=pick(g,'road.club.name','road.club.clubName','road.club.clubPermanentName','road.name','awayTeam.name','away.name'),hs=Number(pick(g,'local.score','local.points','homeScore','score.local')),as=Number(pick(g,'road.score','road.points','awayScore','score.road')),date=pick(g,'date','startDate','startTime','gameDate');return {date,home,away,hs,as}}
async function euroGames(){const seasons=['E2025','E2026'];let out=[];for(const s of seasons){try{const j=await fetchJson(`https://api-live.euroleague.net/v2/competitions/E/seasons/${s}/games`,{retries:1});out.push(...(j.data||j.games||[]).map(parseELGame).filter(x=>x.home&&x.away&&Number.isFinite(x.hs)&&Number.isFinite(x.as)))}catch(e){console.warn('EuroLeague season',s,e.message)}}return out}
async function writeBoard(league,file,source,odds,games,opts,note){const prev=await previous(file),history=prev?.history||[];const b=baseBoard(league,source,note);if(odds.length&&games.length){const z=buildEntries(league,odds,games,opts);b.upcoming=z.upcoming;b.radar=z.radar;b.meta.data_health=games.length>40?'GOOD':'LIMITED';b.meta.market_health='LIVE';b.meta.risk_mode='PAPER';b.meta.model_health=history.length>=100?'WARM':'COLD';b.risk.mode='PAPER';b.risk.exposure_units=z.upcoming.filter(x=>x.verdict==='PAPER BET').reduce((s,x)=>s+(x.stake_units||0),0);b.history=history;b.stats=metrics(history);b.learning.calibration.active=history.length>=40;b.integrity.historical_games=games.length;b.integrity.market_events=odds.length}else{b.history=history;b.stats=metrics(history);b.meta.note=note||'Feed incompleto: sistema fail-closed, nessun segnale inventato.'}await fs.writeFile(path.join(DATA,file),JSON.stringify(b,null,2));return b}
async function main(){await fs.mkdir(DATA,{recursive:true});let nbaOdds=[],elOdds=[],ng=[],eg=[];try{[nbaOdds,elOdds,ng,eg]=await Promise.all([oddsFor('basketball_nba'),oddsFor('basketball_euroleague'),nbaGames(),euroGames()])}catch(e){console.warn('provider error',e.message)}const nba=await writeBoard('NBA','nba-quant-board.json','BALLDONTLIE + The Odds API',nbaOdds,ng,{availability:BDL_KEY?'LIMITED':'UNKNOWN',requireAvailability:false},!ODDS_KEY||!BDL_KEY?'Configura ODDS_API_KEY e BDL_API_KEY per il feed NBA completo.':'Pipeline NBA live attiva in paper mode.');const el=await writeBoard('EUROLEAGUE','euroleague-quant-board.json','EuroLeague public feed + The Odds API',elOdds,eg,{availability:'LIMITED',requireAvailability:false},!ODDS_KEY?'Configura ODDS_API_KEY; il feed statistico EuroLeague non richiede chiave.':'Pipeline EuroLeague live attiva; roster availability penalizzata finché non verificata.');console.log(JSON.stringify({ok:true,nba:{games:ng.length,market:nbaOdds.length,signals:nba.upcoming.length},euroleague:{games:eg.length,market:elOdds.length,signals:el.upcoming.length}},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});
