import {analyzeMarket,closingLineValue} from './quant-engine.mjs';

const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^a-z0-9]+/g,' ').trim();
const hoursBetween=(future,now)=>{const a=new Date(future).getTime(),b=new Date(now).getTime();return Number.isFinite(a)&&Number.isFinite(b)?(a-b)/3600000:null};
const pickSide=(row,team)=>norm(team)===norm(row.home_team)?'home':norm(team)===norm(row.away_team)?'away':null;
const marketFor=(row,team)=>{const side=pickSide(row,team);if(side==='home')return {odds:row.market_home_odds,other:row.market_away_odds,prob:row.market_home_prob};if(side==='away')return {odds:row.market_away_odds,other:row.market_home_odds,prob:row.market_away_prob};return {odds:null,other:null,prob:null}};
const anomaly=reasons=>(reasons||[]).some(r=>['EV_ANOMALY','MODEL_MARKET_GAP','MARKET_INTEGRITY'].includes(r));

export function initializePredictionLock(candidate,nowIso){const bet=candidate.verdict==='PAPER BET';return {...candidate,prediction_locked_at:candidate.predicted_at||nowIso,lock_model_prob:candidate.model_prob,lock_pick_team:candidate.pick_team,lock_data_quality:candidate.data_quality,lock_disagreement:candidate.model_disagreement,lock_uncertainty:candidate.uncertainty,lock_model_sample:candidate.model_sample,lock_challenger_gap:candidate.challenger_gap,lock_availability_status:candidate.availability_status,lock_immutable:true,current_best_odds:candidate.best_odds,live_clv_proxy:0,bet_locked_at:bet?nowIso:null,bet_odds:bet?candidate.best_odds:null,locked_stake_units:bet?candidate.stake_units:0}}

export function repricePredictionLock(old,candidate,nowIso){const pickTeam=old.lock_pick_team||old.pick_team,market=marketFor(candidate,pickTeam),hrs=hoursBetween(old.start_at,nowIso),flip=!!candidate.pick_team&&norm(candidate.pick_team)!==norm(pickTeam);const base={...old,hours_to_start:hrs,current_model_pick:candidate.pick_team||old.current_model_pick,model_flip_detected:flip,market_books:candidate.market_books,odds_age_min:candidate.odds_age_min,market_dispersion:candidate.market_dispersion,market_stability:candidate.market_stability,market_overround:candidate.market_overround,market_home_odds:candidate.market_home_odds,market_away_odds:candidate.market_away_odds,market_home_prob:candidate.market_home_prob,market_away_prob:candidate.market_away_prob,market_families:candidate.market_families,market_ladder:candidate.market_ladder,basketball_intel:candidate.basketball_intel,refreshed_at:nowIso,market_status:'LIVE'};if(!(market.odds>1&&market.other>1&&Number.isFinite(market.prob)))return {...base,market_status:'UNAVAILABLE'};
  if(old.verdict==='PAPER BET'){const betOdds=old.bet_odds||old.best_odds;return {...base,best_odds:betOdds,current_best_odds:market.odds,market_prob:market.prob,live_clv_proxy:closingLineValue(betOdds,market.odds),signal_state:'PAPER BET'};}
  const availability=candidate.availability_status||old.lock_availability_status||'LIMITED',penalty=availability==='VERIFIED'?0:.018;
  const a=analyzeMarket({engineProbs:[old.lock_model_prob??old.model_prob],engineWeights:[1],oddsPick:market.odds,oddsOther:market.other,marketProb:market.prob,overround:candidate.market_overround,uncertainty:old.lock_uncertainty??old.uncertainty??0,disagreement:old.lock_disagreement??old.model_disagreement??0,dataQuality:old.lock_data_quality??old.data_quality??0,marketBooks:candidate.market_books||0,oddsAgeMin:candidate.odds_age_min??999,availabilityStatus:availability,requireAvailability:!!old.require_availability,availabilityPenalty:penalty,marketStability:candidate.market_stability||0,sampleSize:old.lock_model_sample??old.model_sample,challengerGap:old.lock_challenger_gap??old.challenger_gap??0});
  const review=anomaly(a.gateReasons),becameBet=a.decision==='PAPER BET';return {...base,verdict:a.decision,signal_state:review?'REVIEW':a.decision,best_odds:market.odds,current_best_odds:market.odds,raw_ev:a.rawEV,robust_ev:a.robustEV,model_prob:old.lock_model_prob??old.model_prob,market_prob:a.marketProb,edge:a.edge,model_market_gap:a.modelMarketGap,confidence:a.confidence,stake_units:a.stakeUnits,opportunity:a.opportunity,reason_codes:a.gateReasons,wait_reason:a.gateReasons.length?`${review?'Integrity review':'Gate'}: ${a.gateReasons.join(', ')}`:null,live_clv_proxy:0,bet_locked_at:becameBet?nowIso:null,bet_odds:becameBet?market.odds:null,locked_stake_units:becameBet?a.stakeUnits:0};}

export function mergePredictionLocks(previous=[],candidates=[],nowIso=new Date().toISOString()){const prevById=new Map(previous.filter(x=>x?.event_id).map(x=>[x.event_id,x])),seen=new Set(),out=[];for(const c of candidates){const old=prevById.get(c.event_id);out.push(old?repricePredictionLock(old,c,nowIso):initializePredictionLock(c,nowIso));seen.add(c.event_id)}for(const old of previous){if(!old?.event_id||seen.has(old.event_id))continue;const hrs=hoursBetween(old.start_at,nowIso);if(hrs!=null&&hrs>-4)out.push({...old,hours_to_start:hrs,market_status:'UNAVAILABLE',refreshed_at:nowIso})}return out}

function findResult(lock,games){const start=new Date(lock.start_at).getTime();let best=null,bestDiff=Infinity;for(const g of games||[]){if(norm(g.home)!==norm(lock.home_team)||norm(g.away)!==norm(lock.away_team))continue;const t=new Date(g.date).getTime();const diff=Math.abs(t-start);if(Number.isFinite(diff)&&diff<bestDiff&&diff<=30*3600000){best=g;bestDiff=diff}}return best}
function settleOne(lock,g,nowIso){const pickTeam=lock.lock_pick_team||lock.pick_team||String(lock.pick_name||'').replace(/\s+ML$/i,''),winner=g.hs>g.as?g.home:g.away,outcome=norm(pickTeam)===norm(winner),isBet=lock.verdict==='PAPER BET',stake=isBet?(lock.locked_stake_units??lock.stake_units??0):0,odds=isBet?(lock.bet_odds??lock.best_odds):null,profit=isBet&&Number.isFinite(odds)?(outcome?stake*(odds-1):-stake):null,close=lock.current_best_odds||odds,clv=isBet&&odds>1&&close>1?closingLineValue(odds,close):null;return {...lock,status:'SETTLED',settled_at:nowIso,outcome,winner,home_score:g.hs,away_score:g.as,profit_units:profit,closing_odds_proxy:close,clv_proxy:clv}}

export function settleLocks(upcoming=[],history=[],games=[],nowIso=new Date().toISOString()){const now=new Date(nowIso).getTime(),histMap=new Map();for(const h of history||[]){const key=h.event_id||h.audit_id;if(key)histMap.set(key,h)}for(const [key,h] of [...histMap]){if(h.status!=='PENDING_SETTLEMENT')continue;const g=findResult(h,games);if(g)histMap.set(key,settleOne(h,g,nowIso))}const active=[];for(const lock of upcoming||[]){const hrs=(new Date(lock.start_at).getTime()-now)/3600000;if(hrs>-3){active.push({...lock,hours_to_start:hrs});continue}const g=findResult(lock,games),key=lock.event_id||lock.audit_id;if(!key)continue;if(g)histMap.set(key,settleOne(lock,g,nowIso));else histMap.set(key,{...lock,status:'PENDING_SETTLEMENT',pending_since:nowIso})}return {activeUpcoming:active,history:[...histMap.values()].sort((a,b)=>new Date(b.start_at||0)-new Date(a.start_at||0))}}
