(()=>{
'use strict';
const css=`
.matchDetailBackdrop{position:fixed;inset:0;background:rgba(2,7,12,.76);backdrop-filter:blur(8px);z-index:80;display:none;align-items:flex-end;justify-content:center;padding:12px}.matchDetailBackdrop.open{display:flex}.matchDetail{width:min(920px,100%);max-height:min(88vh,920px);overflow:auto;border:1px solid #31516f;border-radius:24px;background:linear-gradient(180deg,#0f2236,#07121e);box-shadow:0 30px 90px rgba(0,0,0,.55);padding:16px}.mdTop{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;position:sticky;top:-16px;background:rgba(9,21,34,.96);backdrop-filter:blur(12px);padding:14px 0 10px;z-index:2}.mdEyebrow{font-size:7px;font-weight:1000;letter-spacing:.15em;color:var(--c)}.mdTitle{font-size:20px;font-weight:1000;margin-top:5px;line-height:1.08}.mdSub{font-size:8px;color:var(--muted);margin-top:5px;line-height:1.45}.mdClose{border:1px solid var(--line2);background:var(--p2);color:#fff;width:38px;height:38px;border-radius:12px;font-size:18px;cursor:pointer}.mdHero{display:grid;grid-template-columns:1.15fr .85fr;gap:9px;margin-top:4px}.mdBox,.mdTeam,.mdMarket{border:1px solid var(--line);border-radius:16px;background:rgba(11,23,37,.92);padding:12px}.mdLean{font-size:24px;font-weight:1000;letter-spacing:-.04em}.mdScore{font-size:30px;font-weight:1000;margin-top:5px}.mdGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:8px}.mdStat{border:1px solid var(--line);border-radius:11px;padding:8px;min-width:0}.mdStat b{display:block;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mdStat span{display:block;font-size:6.4px;color:var(--muted);margin-top:3px}.mdTeams{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.mdTeam h3{font-size:11px;margin:0 0 8px}.mdTeamGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.mdMarket{margin-top:9px;border-color:rgba(66,216,155,.28)}.mdMarket.test{border-color:rgba(242,188,86,.35)}.mdMarketTitle{font-size:13px;font-weight:1000}.mdReason{margin-top:8px;font-size:8px;line-height:1.55;color:#dce7f1}.mdWarn{margin-top:6px;font-size:7.5px;line-height:1.5;color:var(--a)}.mdFooter{margin-top:10px;padding:9px 10px;border-left:3px solid var(--b);background:rgba(100,168,255,.06);border-radius:0 12px 12px 0;color:var(--muted);font-size:7.5px;line-height:1.5}.forecastCard,.betcard{cursor:pointer;transition:transform .15s ease,border-color .15s ease}.forecastCard:active,.betcard:active{transform:scale(.992)}.detailsHint{display:inline-flex;margin-top:9px;padding:5px 7px;border:1px solid rgba(92,224,236,.28);border-radius:999px;color:#bfeff5;font-size:6.3px;font-weight:950}.forecastCard:focus,.betcard:focus{outline:2px solid rgba(100,168,255,.6);outline-offset:2px}
@media(max-width:620px){.matchDetailBackdrop{padding:0;align-items:flex-end}.matchDetail{border-radius:22px 22px 0 0;max-height:92vh;padding:14px}.mdHero,.mdTeams{grid-template-columns:1fr}.mdGrid{grid-template-columns:repeat(2,1fr)}}`;
function addCss(){if(document.getElementById('matchDetailCss'))return;const s=document.createElement('style');s.id='matchDetailCss';s.textContent=css;document.head.appendChild(s)}
const e=s=>String(s??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const f=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
const pc=v=>Number.isFinite(Number(v))?`${(Number(v)*100).toFixed(1)}%`:'—';
const od=v=>Number.isFinite(Number(v))?Number(v).toFixed(2):'—';
const signed=(v,d=1)=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(d)}`:'—';
function stat(label,value){return `<div class="mdStat"><b>${e(value)}</b><span>${e(label)}</span></div>`}
function when(x){try{return new Date(x).toLocaleString('it-IT',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return '—'}}
function findRadar(row){const z=D?.radar||[];return z.find(x=>x.event_id===row?.event_id)||z.find(x=>x.home_team===row?.home_team&&x.away_team===row?.away_team)||null}
function teamBlock(name,s,rest){return `<section class="mdTeam"><h3>${e(name)}</h3><div class="mdTeamGrid">${stat('ELO',f(s?.elo,0))}${stat('PARTITE MODELLO',s?.games??'—')}${stat('PUNTI FATTI / G',f(s?.avg_pf,1))}${stat('PUNTI SUBITI / G',f(s?.avg_pa,1))}${stat('MARGINE FORMA',signed(s?.recent_margin,1))}${stat('TOTALE RECENTE',f(s?.recent_total,1))}${stat('RIPOSO',Number.isFinite(Number(rest))?`${f(rest,1)} gg`:'—')}${stat('ULTIMA',s?.last_game?when(s.last_game):'—')}</div></section>`}
function marketBlock(row){if(!row)return '';const q=row.locked_odds||row.best_odds,stake=row.locked_stake_units??row.stake_units??0,test=row.validation_state==='TEST'||row.decision==='TEST VALUE';return `<section class="mdMarket ${test?'test':''}"><div class="mdEyebrow">BETTING VIEW · ${e(row.decision||'WAIT')}</div><div class="mdMarketTitle">${e(row.selection)} @ ${od(q)} · ${e(row.market_label)}</div><div class="mdGrid">${stat('ROBUST EV',Number.isFinite(Number(row.robust_ev))?`${(Number(row.robust_ev)*100).toFixed(1)}%`:'—')}${stat('MODEL',pc(row.robust_prob))}${stat('MERCATO',pc(row.market_prob))}${stat('BET ≥',od(row.price_to_bet))}${stat('BOOK',row.best_book||'—')}${stat('BOOK SCANSIONATI',row.market_books??'—')}${stat('STAKE',`${f(stake,2)}u`)}${stat('CONFIDENCE',row.confidence!=null?`${f(row.confidence,0)}/100`:'—')}</div>${row.case_for?`<div class="mdReason">✅ ${e(row.case_for)}</div>`:''}${row.case_against?`<div class="mdWarn">⚠ ${e(row.case_against)}</div>`:''}<div class="mdFooter">${test?'Mercato ancora in TEST: viene mostrato per ricerca ma non deve essere trattato come segnale validato.':'La giocata resta valida solo finché prezzo e gate rimangono dentro i limiti del motore.'}</div></section>`}
function content(row,kind){const r=kind==='forecast'?row:findRadar(row),home=r?.home_team||row?.home_team,away=r?.away_team||row?.away_team,hs=r?.team_stats?.home||{},as=r?.team_stats?.away||{},homeScore=r?.projected_home_score,awayScore=r?.projected_away_score,winner=r?.projected_winner,wp=r?.projected_winner_prob;return `<div class="mdTop"><div><div class="mdEyebrow">MATCH INTELLIGENCE · ${e(L||'')}</div><div class="mdTitle">${e(away)} @ ${e(home)}</div><div class="mdSub">${e(r?.start_at?when(r.start_at):row?.start_at?when(row.start_at):'—')} · ${e(r?.status||'MODEL')} · dati dal board corrente</div></div><button class="mdClose" aria-label="Chiudi">×</button></div><div class="mdHero"><section class="mdBox"><div class="mdEyebrow">MODEL LEAN</div><div class="mdLean">${e(winner||'Nessun lean')}</div><div class="mdScore">${Number.isFinite(Number(awayScore))?f(awayScore,1):'—'} – ${Number.isFinite(Number(homeScore))?f(homeScore,1):'—'}</div><div class="mdSub">Punteggio proiettato: away – home</div></section><section class="mdBox"><div class="mdGrid">${stat('LEAN',pc(wp))}${stat('HOME WIN',pc(r?.home_win_prob))}${stat('HOME MARGIN',signed(r?.projected_margin,1))}${stat('TOTAL',f(r?.projected_total,1))}${stat('AFFIDABILITÀ',pc(r?.reliability))}${stat('SAMPLE',r?.model_sample??'—')}${stat('σ MARGINE',f(r?.margin_sigma,1))}${stat('σ TOTALE',f(r?.total_sigma,1))}</div></section></div><div class="mdTeams">${teamBlock(away,as,r?.rest?.away)}${teamBlock(home,hs,r?.rest?.home)}</div>${kind==='bet'?marketBlock(row):''}<div class="mdFooter">Pronostico sportivo ≠ scommessa. Il MODEL FORECAST può esistere settimane prima del match; una BEST BET viene emessa solo quando quote fresche, mercato, rischio e Prediction Lock superano i gate.</div>`}
function ensure(){addCss();if(document.getElementById('matchDetailBackdrop'))return;const b=document.createElement('div');b.id='matchDetailBackdrop';b.className='matchDetailBackdrop';b.innerHTML='<div id="matchDetail" class="matchDetail" role="dialog" aria-modal="true"></div>';document.body.appendChild(b);b.addEventListener('click',ev=>{if(ev.target===b||ev.target.closest('.mdClose'))close()});document.addEventListener('keydown',ev=>{if(ev.key==='Escape')close()})}
function open(row,kind){ensure();const b=document.getElementById('matchDetailBackdrop'),m=document.getElementById('matchDetail');m.innerHTML=content(row,kind);b.classList.add('open');document.body.style.overflow='hidden';m.scrollTop=0}
function close(){const b=document.getElementById('matchDetailBackdrop');if(b)b.classList.remove('open');document.body.style.overflow=''}
function decorate(){const forecasts=[...document.querySelectorAll('#forecastGrid .forecastCard')],fz=D?.radar||[];forecasts.forEach((card,i)=>{card.tabIndex=0;card.dataset.detailKind='forecast';card.dataset.detailIndex=String(i);if(!card.querySelector('.detailsHint'))card.insertAdjacentHTML('beforeend','<span class="detailsHint">TOCCA · STATISTICHE COMPLETE</span>')});const bets=[...document.querySelectorAll('#bestGrid .betcard')],bz=D?.best_bets||[];bets.forEach((card,i)=>{card.tabIndex=0;card.dataset.detailKind='bet';card.dataset.detailIndex=String(i);if(!card.querySelector('.detailsHint'))card.insertAdjacentHTML('beforeend','<span class="detailsHint">TOCCA · MATCH INTELLIGENCE</span>')})}
function activate(card){const kind=card.dataset.detailKind,i=Number(card.dataset.detailIndex),row=kind==='forecast'?(D?.radar||[])[i]:(D?.best_bets||[])[i];if(row)open(row,kind)}
document.addEventListener('click',ev=>{const c=ev.target.closest('[data-detail-kind]');if(c&&!ev.target.closest('button,input,a'))activate(c)});document.addEventListener('keydown',ev=>{if((ev.key==='Enter'||ev.key===' ')&&ev.target.matches('[data-detail-kind]')){ev.preventDefault();activate(ev.target)}});
const obs=new MutationObserver(()=>decorate());
function boot(){ensure();decorate();const a=document.getElementById('forecastGrid'),b=document.getElementById('bestGrid');if(a)obs.observe(a,{childList:true});if(b)obs.observe(b,{childList:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();