(()=>{
'use strict';
const M=globalThis.CourtQuantMath;
if(!M)return;
const css=`
.quantRibbon{margin-top:10px;border:1px solid rgba(242,188,86,.24);border-radius:13px;background:linear-gradient(135deg,rgba(242,188,86,.045),rgba(100,168,255,.035));overflow:hidden}.quantRibbon summary{list-style:none;cursor:pointer;padding:9px 10px;display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:7px;font-weight:1000;color:#f4dfaa;letter-spacing:.08em}.quantRibbon summary::-webkit-details-marker{display:none}.quantRibbon[open] summary{border-bottom:1px solid var(--line)}.quantMetrics{display:grid;grid-template-columns:repeat(6,1fr);gap:5px;padding:9px}.quantMetric{border:1px solid var(--line);border-radius:9px;padding:7px;min-width:0;background:rgba(5,14,23,.42)}.quantMetric b{display:block;font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.quantMetric span{display:block;color:var(--muted);font-size:5.8px;margin-top:2px}.quantFoot{padding:0 9px 9px;color:var(--muted);font-size:6.6px;line-height:1.45}.quantLab{border-color:rgba(242,188,86,.3)!important;background:radial-gradient(circle at 100% 0,rgba(242,188,86,.055),transparent 17rem),linear-gradient(180deg,#0f2134,#091521)!important}.quantFormulaGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:10px}.quantFormula{border:1px solid var(--line);border-radius:12px;padding:10px;background:rgba(5,14,23,.38)}.quantFormula b{display:block;font-size:9px}.quantEq{font:700 8px "SFMono-Regular",Consolas,monospace;color:#f2e6c7;margin:6px 0 3px}.quantFormula span{display:block;color:var(--muted);font-size:6.5px;line-height:1.45}.quantHero{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:9px;position:relative;z-index:2}.quantHero>div{border:1px solid rgba(242,188,86,.19);border-radius:10px;padding:7px;background:rgba(5,14,23,.32)}.quantHero b{display:block;font-size:9px}.quantHero span{display:block;color:var(--muted);font-size:5.8px;margin-top:2px}
@media(max-width:760px){.quantMetrics{grid-template-columns:repeat(3,1fr)}.quantFormulaGrid{grid-template-columns:1fr 1fr}.quantHero{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.quantFormulaGrid{grid-template-columns:1fr}}
`;
function injectCss(){if(document.getElementById('courtQuantCss'))return;const s=document.createElement('style');s.id='courtQuantCss';s.textContent=css;document.head.appendChild(s)}
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const pct=v=>Number.isFinite(v)?(v*100).toFixed(1)+'%':'—';
const dec=v=>Number.isFinite(v)?v.toFixed(2):'—';
const signed=v=>Number.isFinite(v)?(v>=0?'+':'')+(v*100).toFixed(1)+'%':'—';
function rowMath(x){const p=num(x?.robust_prob),mp=num(x?.market_prob),o=num(x?.locked_odds||x?.best_odds),min=num(x?.price_to_bet),fair=M.fairOdds(p),be=M.impliedProbability(o),edge=M.probabilityEdge(p,mp),ev=M.expectedValue(p,o),kelly=M.fractionalKelly(p,o,.25,.02),cush=M.priceCushion(o,min);return{p,mp,o,fair,be,edge,ev,kelly,cush}}
function ribbon(x){const z=rowMath(x),gap=Number.isFinite(z.edge)&&Math.abs(z.edge)>.12?' · MODEL/MARKET GAP ELEVATO':'';return `<details class="quantRibbon"><summary><span>∑ QUANT RIBBON · FAIR PRICE / EDGE / SIZING</span><span>${signed(z.ev)}</span></summary><div class="quantMetrics"><div class="quantMetric"><b>${dec(z.fair)}</b><span>FAIR ODDS</span></div><div class="quantMetric"><b>${pct(z.be)}</b><span>BREAK-EVEN</span></div><div class="quantMetric"><b>${pct(z.mp)}</b><span>DE-VIG MARKET</span></div><div class="quantMetric"><b>${signed(z.edge)}</b><span>P-MARKET EDGE</span></div><div class="quantMetric"><b>${signed(z.ev)}</b><span>EV @ PRICE</span></div><div class="quantMetric"><b>${pct(z.kelly)}</b><span>¼ KELLY · CAP 2%</span></div></div><div class="quantFoot">EV = p·quota − 1 · fair odds = 1/p · Kelly pieno = (bp−q)/b. Il Kelly mostrato è solo riferimento matematico paper, frazionato al 25% e cappato al 2%; non sostituisce i gate di data quality, validazione, esposizione e freshness.${gap}</div></details>`}
function decorateCards(){const rows=D?.best_bets||[],cards=[...document.querySelectorAll('#bestGrid .betcard')];cards.forEach((c,i)=>{if(c.querySelector('.quantRibbon')||!rows[i])return;c.insertAdjacentHTML('beforeend',ribbon(rows[i]))})}
function decorateHero(){const host=document.querySelector('.heroGrid>div:first-child');if(!host||host.querySelector('.quantHero'))return;const x=D?.hero||D?.best_bets?.[0]||null;if(!x)return;const z=rowMath(x);host.insertAdjacentHTML('beforeend',`<div class="quantHero"><div><b>${dec(z.fair)}</b><span>FAIR ODDS</span></div><div><b>${pct(z.be)}</b><span>BREAK-EVEN</span></div><div><b>${signed(z.edge)}</b><span>EDGE VS MARKET</span></div><div><b>${pct(z.kelly)}</b><span>¼ KELLY MATH</span></div></div>`)}
function ensureLab(){const host=document.getElementById('model')||document.getElementById('desk');if(!host||document.getElementById('courtQuantLab'))return;const card=document.createElement('article');card.id='courtQuantLab';card.className='card quantLab';card.innerHTML=`<div class="head"><div><h2>Quant math lab</h2><div class="sub">Le formule spiegano il prezzo. Non trasformano un mercato non validato in una giocata.</div></div><span class="pill">V5 MATH</span></div><div class="quantFormulaGrid"><div class="quantFormula"><b>Implied probability</b><div class="quantEq">pᵢ = 1 / quota</div><span>Probabilità di pareggio grezza incorporata nella quota.</span></div><div class="quantFormula"><b>Two-way de-vig</b><div class="quantEq">pA = (1/oA) / Σ(1/o)</div><span>Rimuove proporzionalmente il margine del bookmaker da un mercato a due esiti.</span></div><div class="quantFormula"><b>Expected value</b><div class="quantEq">EV = p·o − 1</div><span>Rendimento atteso per unità alla quota corrente, prima di errori di modello e costi reali.</span></div><div class="quantFormula"><b>Probability edge</b><div class="quantEq">Edge = pmodel − pmarket</div><span>Distanza tra probabilità robusta del modello e consenso de-vig del mercato.</span></div><div class="quantFormula"><b>Fair odds</b><div class="quantEq">ofair = 1 / pmodel</div><span>Quota teorica coerente con la probabilità robusta del modello.</span></div><div class="quantFormula"><b>Fractional Kelly</b><div class="quantEq">f¼ = 0.25·(bp−q)/b</div><span>Riferimento paper di sizing; il terminale applica un cap visivo del 2% e non bypassa i risk gate.</span></div><div class="quantFormula"><b>Brier score</b><div class="quantEq">BS = mean((p−y)²)</div><span>Calibrazione delle probabilità: più basso è meglio.</span></div><div class="quantFormula"><b>Log loss</b><div class="quantEq">−mean[y log p +(1−y)log(1−p)]</div><span>Penalizza fortemente la falsa sicurezza.</span></div><div class="quantFormula"><b>Price cushion</b><div class="quantEq">C = ocurrent / omin − 1</div><span>Quanto la quota corrente supera il prezzo minimo richiesto dal modello.</span></div></div>`;host.prepend(card)}
function refreshQuant(){injectCss();ensureLab();decorateCards();decorateHero()}
const baseRenderBets=globalThis.renderBets;if(typeof baseRenderBets==='function')globalThis.renderBets=function(){const r=baseRenderBets.apply(this,arguments);queueMicrotask(refreshQuant);return r};
const baseRenderHero=globalThis.renderHero;if(typeof baseRenderHero==='function')globalThis.renderHero=function(){const r=baseRenderHero.apply(this,arguments);queueMicrotask(()=>{const old=document.querySelector('.quantHero');old?.remove();decorateHero()});return r};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(refreshQuant,0));else setTimeout(refreshQuant,0);
window.addEventListener('court-edge:refresh',refreshQuant);
})();
