export const VERSION='CEP-3.0.0';
export const DEFAULT_GATES={minRobustEV:.025,minDQ:70,maxDisagreement:.10,maxUncertainty:.10,minBooks:2,maxOddsAgeMin:90,maxStake:.65,maxExposure:3};
export function clamp(v,a=0,b=1){return Math.max(a,Math.min(b,v))}
export function logistic(x){return 1/(1+Math.exp(-x))}
export function logit(p){p=clamp(p,1e-9,1-1e-9);return Math.log(p/(1-p))}
export function blendProbabilities(parts,weights){if(!parts.length)throw new Error('parts required');const ws=weights?.length===parts.length?weights:parts.map(()=>1);const z=parts.reduce((s,p,i)=>s+logit(clamp(p))*ws[i],0)/ws.reduce((a,b)=>a+b,0);return clamp(logistic(z),.02,.98)}
export function devigTwoWay(oddsA,oddsB){if(!(oddsA>1&&oddsB>1))throw new Error('decimal odds > 1 required');const a=1/oddsA,b=1/oddsB,t=a+b;return {a:a/t,b:b/t,overround:t-1}}
export function expectedValue(prob,odds){return prob*odds-1}
export function robustProbability(prob,{uncertainty=0,disagreement=0,dataQuality=100,availabilityPenalty=0}={}){const dqPenalty=(100-clamp(dataQuality,0,100))/100*.07;const penalty=clamp(uncertainty,0,.3)*.45+clamp(disagreement,0,.3)*.30+dqPenalty+clamp(availabilityPenalty,0,.08);return clamp(prob-penalty,.02,.98)}
export function kellyFraction(prob,odds){if(!(odds>1))return 0;const b=odds-1,q=1-prob;return Math.max(0,(b*prob-q)/b)}
export function stakeUnits({prob,odds,confidence=70,bankrollUnits=100,maxStake=.65}){const k=kellyFraction(prob,odds);const scaled=k*.20*clamp(confidence/100,.35,1);return Math.min(maxStake,Math.max(0,scaled*bankrollUnits/100))}
export function opportunityScore({robustEV=0,confidence=0,dataQuality=0,marketStability=0}){return clamp((clamp(robustEV/.12)*.38+clamp(confidence/100)*.28+clamp(dataQuality/100)*.18+clamp(marketStability/100)*.16)*100,0,100)}
export function gateDecision(x,g=DEFAULT_GATES){const reasons=[];if(x.robustEV<g.minRobustEV)reasons.push('ROBUST_EV');if(x.dataQuality<g.minDQ)reasons.push('DATA_QUALITY');if(x.disagreement>g.maxDisagreement)reasons.push('MODEL_DISAGREEMENT');if(x.uncertainty>g.maxUncertainty)reasons.push('UNCERTAINTY');if(x.marketBooks<g.minBooks)reasons.push('MARKET_DEPTH');if(x.oddsAgeMin>g.maxOddsAgeMin)reasons.push('STALE_ODDS');if(x.availabilityStatus==='UNKNOWN'&&x.requireAvailability)reasons.push('AVAILABILITY_UNKNOWN');return {pass:reasons.length===0,reasons}}
export function brierScore(rows){if(!rows.length)return null;return rows.reduce((s,r)=>s+(r.prob-(r.outcome?1:0))**2,0)/rows.length}
export function logLoss(rows){if(!rows.length)return null;return -rows.reduce((s,r)=>{const p=clamp(r.prob,1e-9,1-1e-9);return s+(r.outcome?Math.log(p):Math.log(1-p))},0)/rows.length}
export function closingLineValue(lockOdds,closeOdds){if(!(lockOdds>1&&closeOdds>1))return null;return lockOdds/closeOdds-1}
export function analyzeMarket(input,g=DEFAULT_GATES){const modelProb=blendProbabilities(input.engineProbs,input.engineWeights);const market=devigTwoWay(input.oddsPick,input.oddsOther);const conservativeProb=robustProbability(modelProb,{uncertainty:input.uncertainty,disagreement:input.disagreement,dataQuality:input.dataQuality,availabilityPenalty:input.availabilityPenalty||0});const robustEV=expectedValue(conservativeProb,input.oddsPick);const gate=gateDecision({robustEV,dataQuality:input.dataQuality,disagreement:input.disagreement,uncertainty:input.uncertainty,marketBooks:input.marketBooks,oddsAgeMin:input.oddsAgeMin,availabilityStatus:input.availabilityStatus,requireAvailability:input.requireAvailability},g);const confidence=clamp((1-input.uncertainty)*100-input.disagreement*55-(100-input.dataQuality)*.12-(input.availabilityPenalty||0)*120,0,100);return {modelProb,marketProb:market.a,overround:market.overround,conservativeProb,rawEV:expectedValue(modelProb,input.oddsPick),robustEV,edge:conservativeProb-market.a,confidence,decision:gate.pass?'PAPER BET':'WAIT',gateReasons:gate.reasons,stakeUnits:gate.pass?stakeUnits({prob:conservativeProb,odds:input.oddsPick,confidence,maxStake:g.maxStake}):0,opportunity:opportunityScore({robustEV,confidence,dataQuality:input.dataQuality,marketStability:input.marketStability})}}
