import test from 'node:test';import assert from 'node:assert/strict';import {initializePredictionLock,mergePredictionLocks,repricePredictionLock,settleLocks} from '../lock-engine.mjs';
const now='2026-08-25T20:00:00Z';
const base={event_id:'evt1',league:'NBA',away_team:'Team B',home_team:'Team A',start_at:'2026-08-26T02:00:00Z',predicted_at:now,pick_team:'Team A',pick_name:'Team A ML',model_prob:.60,data_quality:90,model_disagreement:.02,uncertainty:.03,model_sample:50,availability_status:'LIMITED',require_availability:false,market_books:5,odds_age_min:5,market_stability:90,market_dispersion:.01,market_overround:.04,market_home_prob:.53,market_away_prob:.47,market_home_odds:1.65,market_away_odds:2.30,best_odds:1.65,raw_ev:-.01,robust_ev:-.04,confidence:80,stake_units:0,opportunity:45,verdict:'WAIT',signal_state:'WAIT',reason_codes:['ROBUST_EV']};
test('new prediction lock freezes model inputs',()=>{const x=initializePredictionLock(base,now);assert.equal(x.lock_model_prob,.60);assert.equal(x.lock_pick_team,'Team A');assert.equal(x.lock_immutable,true);assert.equal(x.prediction_locked_at,now)});
test('WAIT can become paper BET when price improves without changing locked model',()=>{const old=initializePredictionLock(base,now),cand={...base,predicted_at:'2026-08-25T22:00:00Z',market_home_odds:1.90,market_away_odds:2.05,best_odds:1.90,market_home_prob:.53,market_away_prob:.47};const x=repricePredictionLock(old,cand,'2026-08-25T22:00:00Z');assert.equal(x.model_prob,.60);assert.equal(x.verdict,'PAPER BET');assert.equal(x.bet_odds,1.90);assert.ok(x.locked_stake_units>0)});
test('issued paper BET stays immutable while current price and model flip are audited',()=>{const bet=initializePredictionLock({...base,verdict:'PAPER BET',signal_state:'PAPER BET',best_odds:1.90,stake_units:.20},now),cand={...base,pick_team:'Team B',pick_name:'Team B ML',market_home_odds:1.80,market_away_odds:2.15,market_home_prob:.55,market_away_prob:.45};const x=repricePredictionLock(bet,cand,'2026-08-25T22:00:00Z');assert.equal(x.verdict,'PAPER BET');assert.equal(x.bet_odds,1.90);assert.equal(x.current_best_odds,1.80);assert.equal(x.model_flip_detected,true);assert.ok(x.live_clv_proxy>0)});
test('merge preserves previous lock identity',()=>{const old=initializePredictionLock(base,now),cand={...base,model_prob:.72,market_home_odds:1.90,market_away_odds:2.05};const [x]=mergePredictionLocks([old],[cand],'2026-08-25T22:00:00Z');assert.equal(x.lock_model_prob,.60);assert.equal(x.event_id,'evt1')});
test('settlement computes outcome profit and CLV proxy',()=>{const lock=initializePredictionLock({...base,start_at:'2026-08-25T14:00:00Z',verdict:'PAPER BET',signal_state:'PAPER BET',best_odds:1.90,stake_units:.20},'2026-08-25T10:00:00Z');lock.current_best_odds=1.80;const g={date:'2026-08-25T14:00:00Z',home:'Team A',away:'Team B',hs:110,as:100};const z=settleLocks([lock],[],[g],now);assert.equal(z.activeUpcoming.length,0);assert.equal(z.history[0].status,'SETTLED');assert.equal(z.history[0].outcome,true);assert.ok(Math.abs(z.history[0].profit_units-.18)<1e-9);assert.ok(z.history[0].clv_proxy>0)});

test('result matcher rejects same matchup too far from scheduled game',()=>{const lock=initializePredictionLock({...base,start_at:'2026-08-25T14:00:00Z',verdict:'PAPER BET',signal_state:'PAPER BET',best_odds:1.90,stake_units:.20},'2026-08-25T10:00:00Z');const g={date:'2026-08-27T14:00:00Z',home:'Team A',away:'Team B',hs:110,as:100};const z=settleLocks([lock],[],[g],'2026-08-25T20:00:00Z');assert.equal(z.history[0].status,'PENDING_SETTLEMENT')});
