let league='NBA',data=null,filter='ALL';const $=id=>document.getElementById(id),pct=x=>Number.isFinite(x)?`${(x*100).toFixed(1)}%`:'—',sgn=x=>Number.isFinite(x)?`${x>=0?'+':''}${(x*100).toFixed(1)}%`:'—',odd=x=>Number.isFinite(x)?x.toFixed(2):'—',esc=s=>String(s??'—').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('on',x.id===id));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('on',x.dataset.page===id))}
document.querySelectorAll('[data-page]').forEach(x=>x.addEventListener('click',()=>page(x.dataset.page)));document.querySelectorAll('[data-league]').forEach(x=>x.addEventListener('click',()=>{league=x.dataset.league;document.querySelectorAll('[data-league]').forEach(y=>y.classList.toggle('on',y===x));load()}));document.querySelectorAll('[data-filter]').forEach(x=>x.addEventListener('click',()=>{filter=x.dataset.filter;document.querySelectorAll('[data-filter]').forEach(y=>y.classList.toggle('on',y===x));markets()}));$('bankroll').addEventListener('input',bank);$('unit').addEventListener('input',bank);
const dclass=x=>x==='PAPER BET'?'bet':x==='TEST VALUE'?'test':'wait';
function hero(){const h=data?.hero;if(!h){$('heroState').textContent='NO BET';$('heroState').className='state wait';$('heroTitle').textContent='Nessuna opportunità validata';$('heroSub').textContent='Se prezzo o dati non superano i gate, il terminale resta NO BET.';$('priceGuard').innerHTML='PRICE GUARD · <strong>—</strong>';$('heroOdds').textContent=$('heroEV').textContent=$('heroStake').textContent='—';return}$('heroState').textContent=h.decision==='PAPER BET'?'BEST BET':'TEST VALUE';$('heroState').className=`state ${dclass(h.decision)}`;$('heroTitle').textContent=`${h.selection} @ ${odd(h.locked_odds||h.best_odds)}`;$('heroSub').textContent=`${h.away_team} @ ${h.home_team} · ${h.market_label} · ${h.best_book||'best book'}`;$('priceGuard').innerHTML=`BET SOLO A <strong>≥ ${odd(h.price_to_bet)}</strong> · attuale ${odd(h.locked_odds||h.best_odds)} · ${h.validation_state==='TEST'?'mercato in validazione':'paper tracking lane'}`;$('heroOdds').textContent=odd(h.locked_odds||h.best_odds);$('heroEV').textContent=sgn(h.robust_ev);$('heroStake').textContent=`${(h.locked_stake_units||h.stake_units||0).toFixed(2)}u`}
function betCard(x,i){return `<article class="bet ${x.decision==='TEST VALUE'?'test':''}"><div class="rank">#${i+1} · ${esc(x.decision)}</div><div class="pick">${esc(x.selection)} @ ${odd(x.locked_odds||x.best_odds)}</div><div class="match">${esc(x.away_team)} @ ${esc(x.home_team)} · ${esc(x.market_label)}</div><div class="edge">${sgn(x.robust_ev)} EV</div><div class="four"><div class="mini"><b>${odd(x.price_to_bet)}</b><span>BET ≥</span></div><div class="mini"><b>${pct(x.robust_prob)}</b><span>MODEL</span></div><div class="mini"><b>${esc(x.best_book)}</b><span>BOOK</span></div><div class="mini"><b>${(x.locked_stake_units||x.stake_units||0).toFixed(2)}u</b><span>STAKE</span></div></div><div class="why">✅ ${esc(x.case_for)}</div><div class="against">⚠ ${esc(x.case_against)}</div></article>`}
function bets(){const z=data?.best_bets||[];$('bestCount').textContent=z.length;$('bestGrid').innerHTML=z.length?z.slice(0,12).map(betCard).join(''):'<div class="empty">NO BET. Nessun mercato ha superato i gate.</div>'}
function markets(){let z=data?.markets||[];if(filter==='VALUE')z=z.filter(x=>x.decision!=='WAIT');else if(filter!=='ALL')z=z.filter(x=>x.market_key===filter);$('marketCount').textContent=z.length;$('marketGrid').innerHTML=z.length?z.slice(0,100).map(x=>`<div class="market"><div><strong>${esc(x.selection)}</strong><br><span>${esc(x.away_team)} @ ${esc(x.home_team)} · ${esc(x.best_book)}</span></div><div><strong>${odd(x.best_odds)}</strong><br><span>BET ≥ ${odd(x.price_to_bet)}</span></div><div><strong class="${x.robust_ev>0?'good':'bad'}">${sgn(x.robust_ev)}</strong><br><span>ROBUST EV</span></div><div class="shide"><strong>${pct(x.robust_prob)}</strong><br><span>MODEL</span></div><div class="mhide"><strong>${pct(x.market_prob)}</strong><br><span>MARKET</span></div><div class="mhide"><strong>${Number.isFinite(x.odds_move)?sgn(x.odds_move):'NEW'}</strong><br><span>ODDS MOVE</span></div><div class="mhide"><strong>${Number.isFinite(x.line_move)?`${x.line_move>=0?'+':''}${x.line_move.toFixed(1)}`:'—'}</strong><br><span>LINE MOVE</span></div><div class="shide"><strong>${Number.isFinite(x.synthetic_hold)?sgn(x.synthetic_hold):'—'}</strong><br><span>SYNTH HOLD</span></div></div>`).join(''):'<div class="empty">Nessun mercato disponibile.</div>'}
function live(){const z=data?.live||[];$('liveGrid').innerHTML=z.length?z.map(x=>`<article class="live"><div class="clock">${esc(x.status)} · ${esc(x.time)}</div><div class="pick">${esc(x.away_team)} @ ${esc(x.home_team)}</div><div class="score">${x.away_score} – ${x.home_score}</div><div class="four"><div class="mini"><b>${pct(x.projection?.homeWin)}</b><span>HOME LIVE</span></div><div class="mini"><b>${Number(x.projection?.finalMargin||0).toFixed(1)}</b><span>FINAL MARGIN</span></div><div class="mini"><b>${Number(x.projection?.finalTotal||0).toFixed(1)}</b><span>LIVE TOTAL</span></div><div class="mini"><b>${x.market_groups?.length||0}</b><span>MARKETS</span></div></div><div class="against">${esc(x.note)}</div></article>`).join(''):'<div class="empty">Nessun live nello snapshot. EuroLeague live richiede un feed dedicato/licenziato.</div>'}
function trackCard(k,n){const s=data?.stats?.by_market?.[k]||{};return `<article class="track"><span>${n}</span><strong>${s.sample||0}</strong><div class="four"><div class="mini"><b>${pct(s.roi)}</b><span>ROI</span></div><div class="mini"><b>${pct(s.hit_rate)}</b><span>HIT</span></div><div class="mini"><b>${Number.isFinite(s.profit_units)?s.profit_units.toFixed(2)+'u':'—'}</b><span>P/L</span></div><div class="mini"><b>${Number.isFinite(s.max_drawdown_units)?s.max_drawdown_units.toFixed(2)+'u':'—'}</b><span>DD</span></div></div></article>`}
function track(){$('trackGrid').innerHTML=trackCard('h2h','MONEYLINE')+trackCard('spreads','SPREAD')+trackCard('totals','TOTAL');const h=data?.history||[];$('history').className='history';$('history').innerHTML=h.length?h.slice(0,30).map(x=>`<div class="hist"><div><strong>${esc(x.selection)}</strong><br><span>${esc(x.away_team)} @ ${esc(x.home_team)}</span></div><div>${x.outcome===true?'WIN':x.outcome===false?'LOSS':'PUSH'}<br><span>${esc(x.market_label)}</span></div><div class="${(x.profit_units||0)>0?'good':(x.profit_units||0)<0?'bad':''}">${Number.isFinite(x.profit_units)?(x.profit_units>=0?'+':'')+x.profit_units.toFixed(2)+'u':'—'}</div></div>`).join(''):'<div class="empty">Nessun mercato V4 chiuso ancora.</div>'}
function bank(){const b=Number($('bankroll').value)||0,u=(Number($('unit').value)||1)/100,h=data?.hero,s=h?(h.locked_stake_units||h.stake_units||0):0;$('bankOut').textContent=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(b*u*s)}
function kpis(){$('kBest').textContent=data?.best_bets?.length||0;$('kMarkets').textContent=data?.markets?.length||0;$('kLive').textContent=data?.live?.length||0;$('kClosed').textContent=data?.stats?.closed||0;$('kROI').textContent=pct(data?.stats?.by_market?.h2h?.roi);$('kInjury').textContent=data?.meta?.injury_health||'—';$('kHealth').textContent=data?.meta?.data_health||'—'}
function render(){hero();bets();markets();live();track();bank();kpis()}
async function load(){const f=league==='NBA'?'../data/nba-v4-board.json':'../data/euroleague-v4-board.json';$('sync').textContent='SYNC…';try{const r=await fetch(`${f}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();$('dot').classList.remove('off');$('sync').textContent='BOARD';render()}catch(e){data=null;$('dot').classList.add('off');$('sync').textContent='NO BOARD';render()}}
load();setInterval(()=>{if(!document.hidden)load()},60000);