const ODDS=process.env.ODDS_API_KEY||'',BDL=process.env.BDL_API_KEY||'',REG=process.env.ODDS_REGIONS||'eu';
const COMM=/^(1|true|yes)$/i.test(process.env.COMMERCIAL_MODE||''),ELLIC=/^(1|true|yes)$/i.test(process.env.EUROLEAGUE_COMMERCIAL_LICENSED||'');
const wait=ms=>new Promise(r=>setTimeout(r,ms));let q=Promise.resolve(),next=0;
async function json(url,{headers={},tries=2}={}){let last;for(let i=0;i<=tries;i++){const c=new AbortController(),t=setTimeout(()=>c.abort(),16000);try{const r=await fetch(url,{headers,signal:c.signal});if(r.status===429){const x=Number(r.headers.get('retry-after'))||2;if(i<tries){await wait(Math.min(65000,x*1000));continue}}if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(e){last=e;if(i<tries)await wait(900*(i+1))}finally{clearTimeout(t)}}throw last}
function bdl(url){const run=q.then(async()=>{const w=Math.max(0,next-Date.now());if(w)await wait(w);next=Date.now()+13000;return json(url,{headers:{Authorization:BDL}})});q=run.catch(()=>{});return run}
export async function odds(sport){if(!ODDS)return [];return json(`https://api.the-odds-api.com/v4/sports/${sport}/odds/?regions=${encodeURIComponent(REG)}&markets=h2h,spreads,totals&oddsFormat=decimal&apiKey=${encodeURIComponent(ODDS)}`)}
export async function nbaGames(){if(!BDL)return [];const end=new Date(Date.now()-86400000).toISOString().slice(0,10),start=new Date(Date.now()-300*86400000).toISOString().slice(0,10),out=[];let cur=null;for(let i=0;i<12;i++){const p=new URLSearchParams({start_date:start,end_date:end,per_page:'100'});if(cur!=null)p.set('cursor',String(cur));const j=await bdl(`https://api.balldontlie.io/v1/games?${p}`);out.push(...(j.data||[]));cur=j.meta?.next_cursor;if(!cur)break}return out.filter(g=>g.status_state==='final'||g.status==='Final').map(g=>({date:g.datetime||g.date,home:g.home_team?.full_name,away:g.visitor_team?.full_name,home_id:g.home_team?.id,away_id:g.visitor_team?.id,hs:+g.home_team_score,as:+g.visitor_team_score})).filter(x=>x.home&&x.away&&Number.isFinite(x.hs)&&Number.isFinite(x.as))}
export async function nbaInjuries(){if(!BDL)return {status:'UNKNOWN',rows:[]};try{const j=await bdl('https://api.balldontlie.io/v1/player_injuries?per_page=100');return {status:'VERIFIED',rows:j.data||[]}}catch(e){return {status:'LIMITED',rows:[],error:e.message}}}
export async function nbaLive(){if(!BDL)return [];try{const j=await bdl('https://api.balldontlie.io/v1/box_scores/live');return j.data||[]}catch{return []}}
const pick=(o,...k)=>{for(const x of k){const v=x.split('.').reduce((a,b)=>a?.[b],o);if(v!==undefined&&v!==null&&v!=='')return v}return null};
const parse=g=>({home:pick(g,'local.club.name','local.club.clubName','local.name','homeTeam.name','home.name'),away:pick(g,'road.club.name','road.club.clubName','road.name','awayTeam.name','away.name'),hs:Number(pick(g,'local.score','local.points','homeScore','score.local')),as:Number(pick(g,'road.score','road.points','awayScore','score.road')),date:pick(g,'date','startDate','startTime','gameDate')});
export function euroSeasons(now=new Date()){const y=now.getUTCFullYear(),m=now.getUTCMonth(),s=m>=7?y:y-1;return [`E${s-1}`,`E${s}`]}
export async function euroGames(){if(COMM&&!ELLIC)return [];let out=[];for(const s of euroSeasons()){try{const j=await json(`https://api-live.euroleague.net/v2/competitions/E/seasons/${s}/games`,{tries:1});out.push(...(j.data||j.games||[]).map(parse).filter(x=>x.home&&x.away&&Number.isFinite(x.hs)&&Number.isFinite(x.as)))}catch(e){console.warn('EL',s,e.message)}}return out}
export const commercialMode=()=>COMM;