import fs from 'node:fs/promises';import path from 'node:path';import {pathToFileURL} from 'node:url';
import {V4,norm,buildModel,project,liveProjection,median} from './core.mjs';
import {candidates,injurySummary,groups,settle} from './market.mjs';
import {odds,nbaGames,nbaInjuries,nbaLive,euroGames,commercialMode} from './providers.mjs';
const DATA=path.join(process.cwd(),'data'),ISO=new Date().toISOString(),NOW=new Date(),LOCK_MIN=.75,LOCK_MAX=36,RADAR_DAYS=90;
const prev=async f=>{try{return JSON.parse(await fs.readFile(path.join(DATA,f),'utf8'))}catch{return null}};
const hours=iso=>(new Date(iso)-NOW)/36e5;
const id=(league,e)=>String(e.id||`${league}-${norm(e.away_team)}-${norm(e.home_team)}-${e.commence_time}`).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,96);
const prevMap=b=>new Map((b?.markets||[]).map(x=>[x.market_id,x]));
const gkey=g=>`${norm(g.away)}|${norm(g.home)}|${String(g.date||'').slice(0,10)}`;
function settleOld(history=[],bets=[],games=[]){const fm=new Map(games.map(g=>[gkey(g),g])),h=[...history],active=[];for(const x of bets){if(x.status==='SETTLED'){h.push(x);continue}const g=fm.get(`${norm(x.away_team)}|${norm(x.home_team)}|${String(x.start_at||'').slice(0,10)}`);if(!g){active.push(x);continue}const s=settle(x,g);s?h.unshift(s):active.push(x)}const seen=new Set();return {history:h.filter(x=>{const k=x.bet_id||`${x.market_id}|${x.start_at}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,3000),active}}
function stats(history=[]){const by={};for(const k of ['h2h','spreads','totals']){const z=history.filter(x=>x.status==='SETTLED'&&x.market_key===k&&!x.push&&Number.isFinite(x.profit_units)),stake=z.reduce((s,x)=>s+(x.locked_stake_units??x.stake_units??0),0),pl=z.reduce((s,x)=>s+x.profit_units,0);let eq=0,peak=0,dd=0;for(const x of [...z].reverse()){eq+=x.profit_units;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}by[k]={sample:z.length,roi:stake?pl/stake:null,profit_units:pl,hit_rate:z.length?z.filter(x=>x.profit_units>0).length/z.length:null,max_drawdown_units:dd}}return {closed:history.filter(x=>x.status==='SETTLED').length,by_market:by}}
function historyMap(prev,current){const out={...(prev?.market_history||{})};for(const x of current){const a=Array.isArray(out[x.market_id])?out[x.market_id]:[];a.push({at:ISO,line:x.line,best_odds:x.best_odds,book:x.best_book});out[x.market_id]=a.slice(-18)}return out}
function liveRows(events,boxes,pre){const out=[];for(const g of boxes||[]){if(!['in_progress','scheduled'].includes(g.status_state)&&!/qtr|half|ot/i.test(String(g.status||'')))continue;const home=g.home_team?.full_name,away=g.visitor_team?.full_name,p=pre.get(`${norm(away)}|${norm(home)}`);if(!home||!away||!p)continue;const z=liveProjection(p,g),ev=(events||[]).find(x=>norm(x.home_team)===norm(home)&&norm(x.away_team)===norm(away));out.push({game_id:g.id,home_team:home,away_team:away,home_score:+g.home_team_score,away_score:+g.visitor_team_score,status:g.status,time:g.time,projection:z,market_groups:ev?groups(ev).map(m=>({market_key:m.key,line:m.line,books:m.rows.length,best_a:m.rows.length?Math.max(...m.rows.map(r=>r.oa)):null,best_b:m.rows.length?Math.max(...m.rows.map(r=>r.ob)):null,age_min:m.rows.length?median(m.rows.map(r=>r.age)):null})):[],mode:'LIVE RESEARCH',note:'Refresh GitHub non low-latency: nessun segnale in-play operativo.'})}return out}
function empty(league,source){return {meta:{league,version:V4,updated_at:ISO,status:'PAPER BETA',source,risk_mode:'PAPER_ONLY',strict_no_fabrication:true},hero:null,best_bets:[],markets:[],radar:[],live:[],history:[],stats:{closed:0,by_market:{}},market_history:{},integrity:{strict_no_fabrication:true,featured_markets:['h2h','spreads','totals'],price_to_bet:true,line_movement:true,synthetic_hold:true,commercial_license_gate:true}}}
async function board(league,file,source,events,games,{injStatus='LIMITED',injRows=[],boxes=[]}={}){const old=await prev(file),b=empty(league,source),model=buildModel(games,league),inj=injurySummary(injRows),rolled=settleOld(old?.history||[],old?.best_bets||[],games),hist=rolled.history,pm=prevMap(old),markets=[],radar=[],pre=new Map();for(const ev0 of events||[]){const hrs=hours(ev0.commence_time);if(hrs>RADAR_DAYS*24)continue;const ev={...ev0,id:id(league,ev0)},hid=model.teams.get(norm(ev.home_team))?.id,aid=model.teams.get(norm(ev.away_team))?.id,ir={home:hid!=null?(inj.get(hid)?.risk||0):0,away:aid!=null?(inj.get(aid)?.risk||0):0},p=project(model,ev.home_team,ev.away_team,ev.commence_time,ir);pre.set(`${norm(ev.away_team)}|${norm(ev.home_team)}`,p);if(hrs>0)radar.push({event_id:ev.id,home_team:ev.home_team,away_team:ev.away_team,start_at:ev.commence_time,hours_to_start:hrs,projected_margin:p.margin,projected_total:p.total,model_sample:p.sample,status:hrs<=LOCK_MAX?'LOCK WINDOW':'EARLY RADAR',injuries:{home:hid!=null?inj.get(hid)||null:null,away:aid!=null?inj.get(aid)||null:null}});if(hrs>=LOCK_MIN&&hrs<=LOCK_MAX)markets.push(...candidates({league,ev,projection:p,history:hist,previous:pm,injuryStatus:injStatus}).map(x=>({...x,home_team:ev.home_team,away_team:ev.away_team,start_at:ev.commence_time})))}const eventMap=new Map();for(const m of markets){if(!eventMap.has(m.event_id))eventMap.set(m.event_id,[]);eventMap.get(m.event_id).push(m)}const fresh=[];for(const [eid,z] of eventMap){const x=[...z].filter(x=>x.decision!=='WAIT').sort((a,b)=>(b.opportunity||0)-(a.opportunity||0))[0];if(x)fresh.push({...x,bet_id:`${x.market_id}|${ISO}`,status:'LOCKED',locked_at:ISO,locked_odds:x.best_odds,locked_stake_units:x.stake_units})}const merged=[...rolled.active];for(const x of fresh)if(!merged.some(y=>y.event_id===x.event_id&&y.status!=='SETTLED'))merged.push(x);b.markets=markets.sort((a,b)=>(b.opportunity||0)-(a.opportunity||0));b.radar=radar.sort((a,b)=>a.hours_to_start-b.hours_to_start);b.best_bets=merged.sort((a,b)=>(b.opportunity||0)-(a.opportunity||0));b.hero=b.best_bets[0]||null;b.history=hist;b.stats=stats(hist);b.market_history=historyMap(old,markets);b.meta.data_health=games.length>250?'GOOD':games.length>80?'LIMITED':'THIN';b.meta.market_health=events.length?'LIVE':'NO FEED';b.meta.injury_health=injStatus;b.integrity.historical_games=games.length;b.integrity.market_events=events.length;b.integrity.market_rows=markets.length;if(league==='NBA')b.live=liveRows(events,boxes,pre);await fs.writeFile(path.join(DATA,file),JSON.stringify(b,null,2));return b}
export async function main(){await fs.mkdir(DATA,{recursive:true});const r=await Promise.allSettled([odds('basketball_nba'),odds('basketball_euroleague'),nbaGames(),euroGames(),nbaInjuries(),nbaLive()]),v=r.map((x,i)=>x.status==='fulfilled'?x.value:(i===4?{status:'LIMITED',rows:[]}:[])),[no,eo,ng,eg,inj,boxes]=v;const nba=await board('NBA','nba-v4-board.json','BALLDONTLIE + The Odds API',no,ng,{injStatus:inj.status,injRows:inj.rows,boxes}),el=await board('EUROLEAGUE','euroleague-v4-board.json',commercialMode()?'Licensed EuroLeague provider required + The Odds API':'EuroLeague research feed + The Odds API',eo,eg);console.log(JSON.stringify({ok:true,version:V4,nba:{markets:nba.markets.length,best:nba.best_bets.length,live:nba.live.length},euroleague:{markets:el.markets.length,best:el.best_bets.length}}))}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)main().catch(e=>{console.error(e);process.exitCode=1});